### ISSUE TITLE
Data too long for column 'route'

### ISSUE THREAD

**Issue by carloshc** [jeremykenedy/laravel-logger#1]
Socialite + Laravel Logger:

String data, right truncated: 1406 Data too long for column 'route' at row 1

**Comment by jeremykenedy** [comment]
Yeah, I need to fix the migration...

from 
```
$table->string('route')->nullable();
```

to: 
```
$table-> longText('route')->nullable();
```

Thanks for letting me know and checking out the project!.

**Comment by jeremykenedy** [comment]
I have fixed this in https://github.com/jeremykenedy/laravel-logger/commit/a25ef725516a08934baa9fe069326c893d882955

Thank you again.

**Comment by carloshc** [comment]
Same thing to column `referer` with Google+ integration.
