### ISSUE TITLE
Replace middleware "auth"

### ISSUE THREAD

**Issue by AMAFsoft** [jeremykenedy/laravel-logger#103]
Hi ! 
It would be nice if its possible to be able to replace '**auth**' middleware with another one, like '**employee**' for example.
I can edit the middelware in routes, but not in controllers constructors.

thanks.

**Comment by jeremykenedy** [comment]
You can’t replace Auth but you can add your own middleware via the config or env.

**Comment by AMAFsoft** [comment]
How about **guards**?
