### ISSUE TITLE
Customization Problem or not ? 

### ISSUE THREAD

**Issue by praudpp** [jeremykenedy/laravel-logger#104]
When I try to change html code it dose not respond. Does not change any thing. 
eg.  When I try to change title it dosenot respond any thing. Yes, I tried in Lang also nothing happen.

@section('template_title')
    {{ trans('LaravelLogger::laravel-logger.dashboard.title') }}
@endsection

Any Idea ? Please.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-logger#opening-an-issue
