### ISSUE TITLE
Class 'Illuminate\Foundation\Application' not found with lumen 8.0

### ISSUE THREAD

**Issue by ibrahimMahfuz** [jeremykenedy/laravel-logger#107]
error is in:
`vendor\jeremykenedy\laravel-logger\src\App\Models\Activity.php (line 128)`

`public static function rules($merge = []) {
     if (\Illuminate\Foundation\Application::VERSION < 5.8) {            
         $route_url_check = 'active_url';        
    } else {            
         $route_url_check = 'url';        
}`

**Comment by jeremykenedy** [comment]
If you want to update support for Lumen I will accept a PR. I don't use Lumen enough :P

**Comment by ibrahimMahfuz** [comment]
> If you want to update support for Lumen I will accept a PR. I don't use Lumen enough :P

i've made PR for Lumen 8, thanks
