### ISSUE TITLE
App/config is not over writing vendor/config

### ISSUE THREAD

**Issue by illuminate3** [jeremykenedy/laravel-logger#11]
I was having trouble installing this package until I realized that the app/config file was not taking precedence over the package config file.

I haven't had a chance to do a deeper discovery yet. I will report back if I find a solution.

**Comment by illuminate3** [comment]
@deardooley 
Thanks for the tip! I will try this.

**Comment by saragan** [comment]
just a further note, i found on linux the views overrides were not working, i had to name resources/views/vendor/laravellogger to resources/views/vendor/LaravelLogger 
case sensitive

**Comment by jeremykenedy** [comment]
I setup this package today on Ubuntu 16.04 and it worked fine so. I have tried multiple times to replicate this issue by have not been able to. On both my homestead and on production servers.

**Comment by quatess1** [comment]
having an issue with laravel logged section, it does not display the correct log route after editing or modifying some pages
