### ISSUE TITLE
 FatalThrowableError

### ISSUE THREAD

**Issue by pedramkouasri** [jeremykenedy/laravel-logger#112]
Parse error: syntax error, unexpected '=' 
in UserAgentDetails.php line 105

**Comment by kentdahl** [comment]
> Parse error: syntax error, unexpected '='  in UserAgentDetails.php line 105

@pedramkouasri; 

Upgrade to PHP v7.4, or ensure you have the locale extension in your PHP environment.

If neither of those things are possible, this is a possible workaround:

https://github.com/jeremykenedy/laravel-logger/pull/111/files

Also, read this before opening issue:

https://github.com/jeremykenedy/laravel-logger#opening-an-issue
