### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by PositiveZahid** [jeremykenedy/laravel-logger#113]
I am using laravel-logger 2.4 with laravel 5.7, but recently i have updated from laravel 5.7 to laravel 8. 

This time i installed laravel-logger 4

laravel logger is not working and producing error. 

![Screenshot_1](https://user-images.githubusercontent.com/6300563/102229779-543c4b00-3f16-11eb-9df6-491e54947047.png)

**Comment by PositiveZahid** [comment]
I provided star and followed your instruction.

**Comment by jeremykenedy** [comment]
Manually update your config file or republish it with the force flag

**Comment by PositiveZahid** [comment]
I downloaded the coifing file from github and replace latest file with previous one. Wow its working but. When i wanted to see a single log file on  

**http://fiverr-online.test/activity/log/26649**

it is producing error. 

![Screenshot_1](https://user-images.githubusercontent.com/6300563/102381569-98e9e400-3ff3-11eb-82fd-c3f0e5e2348b.png)

`@if (count($activities) > 10)`

is the issue. I think the variable would be 

`@if (count($userActivities) > 10)`

it is working for me.

**Comment by Enkumicahel** [comment]
@jeremykenedy bro, first of all, thanks for such an amazing platform. I was facing the same issue and only when I set `LARAVEL_LOGGER_MIDDLEWARE_ENABLED=false` it opens the home page. I can see the error is coming from this line in `/vendor/jeremykenedy/laravel-logger/src/App/Http/Traits/ActivityLogger.php`

`        // Validation Instance
        $validator = Validator::make($data, config('laravel-logger.defaultActivityModel')::rules());
`
