### ISSUE TITLE
Breaking 4.2.0

### ISSUE THREAD

**Issue by RinTheWeeb** [jeremykenedy/laravel-logger#116]
Hello,

If you are going to update your package to use PHP8, at least change your major version.

My composer updated to 4.8.0 while im still running PHP 7.3

**Comment by jeremykenedy** [comment]
Not enough info.

**Comment by RinTheWeeb** [comment]
Here is some info:

Version 4.2.0 of your package WILL get downloaded when the machine is running PHP 7.3

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-logger/releases
