### ISSUE TITLE
Class 'Crawler' not found

### ISSUE THREAD

**Issue by karthikw3cert** [jeremykenedy/laravel-logger#12]
After Install jeremykenedy/laravel-logger i got  **FatalThrowableError Class 'Crawler' not found** in ActivityLogger.php line 29

**Comment by tirsope** [comment]
I installed the package and I'm getting the same error. Do you have a resolution for this one? @jeremykenedy

**Comment by jeremykenedy** [comment]
```composer install``` it is missing the dependency: https://github.com/jeremykenedy/laravel-logger/blob/master/composer.json#L22

**Comment by tirsope** [comment]
@jeremykenedy thanks, the dependency is there, but the issue was I had to include the Crawler service provider in the config/app.php

**Comment by nithishpk** [comment]
> @jeremykenedy thanks, the dependency is there, but the issue was I had to include the Crawler service provider in the config/app.php

Which line you have added in config/app.php can you share I am also facing the same issue
