### ISSUE TITLE
Placeholder localization in form-search.blade

### ISSUE THREAD

**Issue by Mokei-it** [jeremykenedy/laravel-logger#121]
Hello there,
please consider localize placeholders in LaravelLogger/partials/form-search.blade.php

`
<input name="description"  placeholder="{{ trans('LaravelLogger::laravel-logger.dashboard.labels.description') }}">
<input name="route" placeholder="{{ trans('LaravelLogger::laravel-logger.drilldown.list-group.labels.route') }}">
<input name="ip_address" placeholder="{{ trans('LaravelLogger::laravel-logger.drilldown.list-group.labels.ip') }}">
`

Thank you for your great work

**Comment by jeremykenedy** [comment]
Thank you
