### ISSUE TITLE
Class 'App\User' not found

### ISSUE THREAD

**Issue by MusheAbdulHakim** [jeremykenedy/laravel-logger#122]
This is a screenshot of the error i get after doing the installation and including the routes.

![error](https://user-images.githubusercontent.com/58814410/119438879-b6dd1280-bd10-11eb-96c4-6c0f96ee370e.png)

**Comment by jeremykenedy** [comment]
Update your env file

https://github.com/jeremykenedy/laravel-logger#environment-file
