### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by Emmanavimex** [jeremykenedy/laravel-logger#125]
am get the error `Class name must be a valid object or a string` when i try to Login, on this line

`// Validation Instance

        $validator = Validator::make($data, config('laravel-logger.defaultActivityModel')::rules());

`

**Comment by jeremykenedy** [comment]
Publish the config file and and clear your cache

**Comment by Emmanavimex** [comment]
what is command of publish

**Comment by Emmanavimex** [comment]
@jeremykenedy , Kindly can you assist me on my code just to show me like how to usage, because i think that i missed something 

i like your package,

**Comment by Emmanavimex** [comment]
example am facing this error again 

`Target class [App\Http\Controllers\jeremykenedy\LaravelLogger\App\Http\Controllers\untaggedController] does not exist.`

am new in laravel

**Comment by Emmanavimex** [comment]
kindly can you assist me on Usage  ?

**Comment by jeremykenedy** [comment]
Check out the readme
