### ISSUE TITLE
Log activity url not working

### ISSUE THREAD

**Issue by zainawan99** [jeremykenedy/laravel-logger#127]
Log activity url not working

**Comment by jeremykenedy** [comment]
I can't replicate

**Comment by zainawan99** [comment]
admin dashboard not showing?

**Comment by zainawan99** [comment]
they have redirected to the dashboard.I m hit the activity URL then they have redirected to dashboard

**Comment by zainawan99** [comment]
any update?

**Comment by zainawan99** [comment]
@jeremykenedy ??

**Comment by jeremykenedy** [comment]
I've been out of town, I'll try and get to it this week

**Comment by zainawan99** [comment]
thankyou

**Comment by zainawan99** [comment]
any update?

**Comment by jeremykenedy** [comment]
Can you please provide detailed replications steps

**Comment by zainawan99** [comment]
i m follow Github doc step

**Comment by jeremykenedy** [comment]
I don't understand the issue. You need to clearly demonstrate it with replication steps. 

At this moment I cannot replicate this issue as explained.

**Comment by zainawan99** [comment]
Hi,

When I open the admin dashboard.If I do a url given in the documentation,
the show does not happen.I am following the ticket right
documentation.Admin model and customer model are separate

**Comment by jozefcuryllo** [comment]
It looks like this package is a bit outdated and not fully compatible with newest Laravel.
First of all, make sure about compatibility of your /layouts/app.blade.php, navigation.blade.php with package's logger/partials/activity-log.blade.php.

I'm also not pretty sure whether translations and sections with `LaravelLogger::` work correctly.

Oh, and it seems to support only bootstrap 3 and 4.

**Comment by zainawan99** [comment]
i m try this is not working admin side but data insert in database properly

**Comment by zainawan99** [comment]
my model name Admin and Route admin.php

**Comment by zainawan99** [comment]
![image](https://user-images.githubusercontent.com/24542584/147322243-d104fb79-b042-4b79-aa73-2f4934e7c407.png)
![image](https://user-images.githubusercontent.com/24542584/147322392-6022e42a-dbf7-4e7a-ac00-38895bed2026.png)

**Comment by zainawan99** [comment]
![image](https://user-images.githubusercontent.com/24542584/147322474-c649a9e3-3628-41ce-9eb8-93d3e86eef11.png)

**Comment by zainawan99** [comment]
![image](https://user-images.githubusercontent.com/24542584/147322509-93426458-da1d-4af5-9504-c8d57f03d188.png)
![image](https://user-images.githubusercontent.com/24542584/147322573-f0c3e198-cb47-4ce5-a1ac-edd318c9c75e.png)
