### ISSUE TITLE
Log activity URL not working

### ISSUE THREAD

**Issue by anubhav217** [jeremykenedy/laravel-logger#132]

**Comment by JamalAbsalimov** [comment]
When I open the page /activity


{"error":{"code":500,"message":"Call to undefined method Laravel\\Lumen\\Routing\\Router::name()","trace":"#0 \/app\/vendor\/laravel\/lumen-framework\/src\/Routing\/Router.php(62): Illuminate\\Support\\ServiceProvider->{closure}(Object(Laravel\\Lumen\\Routing\\Router))\n#1 \/app\/vendor\/illuminate\/support\/Facades\/Facade.php(261): Laravel\\Lumen\\Routing\\Router->group(Array, Object(Closure))\n#2 \/app\/vendor\/jeremykenedy\/laravel-logger\/src\/routes\/web.php(24): Illuminate\\Support\\Facades\\Facade::__callStatic('group', Array)\n#3 \/app\/vendor\/illuminate\/support\/ServiceProvider.php(152): require('\/app\/vendor\/jer...')\n#4 \/app\/vendor\/jeremykenedy\/laravel-logger\/src\/LaravelLoggerServiceProvider.php(83): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('\/app\/vendor\/jer...')\n#5 \/app\/vendor\/laravel\/lumen-framework\/src\/Application.php(233): jeremykenedy\\LaravelLogger\\LaravelLoggerServiceProvider->register()\n#6 \/app\/bootstrap\/app.php(108): Laravel\\Lumen\\Application->register(Object(jeremykenedy\\LaravelLogger\\LaravelLoggerServiceProvider))\n#7 \/app\/public\/index.php(14): require('\/app\/bootstrap\/...')\n#8 {main}"}}

**Comment by jeremykenedy** [comment]
Luman doesn't have that method
