### ISSUE TITLE
Calling static trait methods is deprecated

### ISSUE THREAD

**Issue by filipz-proglove** [jeremykenedy/laravel-logger#134]
Hello there.
I am facing some warnings with this package, that I wanted to bring to attention. This wasn't the case until I updated PHP.
It seems that calling some static trait methods is deprecated. As can be seen below : 

```
[00:48:07] LOG.warning: Calling static trait method jeremykenedy\LaravelLogger\App\Http\Traits\ActivityLogger::activity is deprecated, it should only be called on a class using the trait in vendor/jeremykenedy/laravel-logger/src/App/Http/Middleware/LogActivity.php on line 24

```

```
WARNINGLOG
[00:48:07] LOG.warning: Calling static trait method jeremykenedy\LaravelLogger\App\Http\Traits\ActivityLogger::storeActivity is deprecated, it should only be called on a class using the trait in /vendor/jeremykenedy/laravel-logger/src/App/Http/Traits/ActivityLogger.php on line 83
```

PHP version : 

```
PHP 8.1.0 (cli) (built: Nov 23 2021 18:56:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies
```
OS : 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```
Also affects other package by the same author -  `LaravelBlocker` 

`jeremykenedy\LaravelBlocker\App\Traits\IpAddressDetails::checkIP is deprecated, it should only be called on a class using the trait in /vendor/jeremykenedy/laravel-blocker/src/App/Traits/LaravelCheckBlockedTrait.php on line 22`

**Comment by filipz-proglove** [comment]
In fact when combined with this issue : 

https://github.com/barryvdh/laravel-debugbar/issues/1261

The debug bar becomes quite populated with useless warnings.

**Comment by arborrow** [comment]
I looked at a [patch for a similar Drupal-related issue](https://www.drupal.org/files/issues/2021-09-27/3239442-4.patch) and suspect that it may be simply a matter or replacing the trait name with static. I will let @jeremykenedy look at that and test the functionality.

**Comment by ajitdas123** [comment]
Hi @jeremykenedy ,
Can we update this? 
I checked changing ` public static function activity($description = null, $details = null)` to ` public function activity($description = null, $details = null)` inside `ActivityLogger`
And using it like this
```
           //ActivityLogger::activity($description);
            $this->activity($description);
            
 ```
Does remove the warning logs. But don't know the drawback of making this function non-static. This would be nice if we could get rid of these warnings,

**Comment by jeremykenedy** [comment]
Solved with https://github.com/jeremykenedy/laravel-logger/pull/166

**Comment by jeremykenedy** [comment]
Rolling into issue #166
