### ISSUE TITLE
Laravel 9.x support - illuminate/view

### ISSUE THREAD

**Issue by arborrow** [jeremykenedy/laravel-logger#137]
In preparation for the release of Laravel 9, I figured I would create this issue. 

Problem 1
    - illuminate/view[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/view[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/view[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.15) does not satisfy that requirement.
    - Root composer.json requires jeremykenedy/laravel-logger ^6.0 -> satisfiable by jeremykenedy/laravel-logger[v6.0.0].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - jeremykenedy/laravel-logger v6.0.0 requires **laravelcollective/html ^5.4|^5.5|^5.6|^5.7|^5.8|^6.0|^7.0|^8.0** -> satisfiable by laravelcollective/html[v6.2.0, v6.2.1, 6.x-dev].
    - laravelcollective/html[v6.2.0, ..., 6.x-dev] require **illuminate/view ^6.0|^7.0|^8.0** -> satisfiable by illuminate/view[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/view[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/view and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

**Comment by jeremykenedy** [comment]
Laravel just keeps jumping and changing so fast 😅 I even feel using blade is a little outdated 😅

**Comment by arborrow** [comment]
I feel your pain, this is one of 10 packages I use that will need to be updated in preparation for Laravel 9. Thanks for your continued support of this package. It allowed me to implement logging of user activity in my app very easily.

**Comment by arborrow** [comment]
Jeremy - I went ahead and created the following pull request https://github.com/jeremykenedy/laravel-logger/pull/141 - hopefully that helps. Peace - Anthony

**Comment by arborrow** [comment]
https://github.com/LaravelCollective/html/tree/v6.3.0 Version 6.3.0 of the LaravelCollect/html package updates its composer.json for Laravel 9 so no updates are needed. I am going to go ahead and close this issue as I did the pull request.
