### ISSUE TITLE
sudo chmod -R 755 ../laravel-auth

### ISSUE THREAD

**Issue by rextech03** [jeremykenedy/laravel-logger#14]
Sincerely I read the instruction before making an issue but I do not know what step to take about this as i get 'sudo' not a recognised command when i run this 'sudo chmod -R 755 ../laravel-auth' please what do i do am stucked.

**Comment by jeremykenedy** [comment]
Please see issue: https://github.com/jeremykenedy/laravel-auth/issues/165

Thank you again for checking out the project :)
