### ISSUE TITLE
Call to undefined function jeremykenedy\LaravelLogger\config_path() 

### ISSUE THREAD

**Issue by astritshuli** [jeremykenedy/laravel-logger#143]
Hello. I followed the steps for lumen configuration but i am reciveing this error when i run: `php artisan migrate`. 
_Call to undefined function jeremykenedy\LaravelLogger\config_path()_ 

![image](https://user-images.githubusercontent.com/40426603/169307347-73c659b1-c420-474f-b3f2-f28ef4677595.png)

**Comment by jeremykenedy** [comment]
See this for your Lumen app 
https://gist.github.com/mabasic/21d13eab12462e596120#file-helpers-php
