### ISSUE TITLE
config file not loading in project config folder

### ISSUE THREAD

**Issue by ozanmora** [jeremykenedy/laravel-logger#16]
Hello,

Firstly thanks for this plugin. But, I have an issue. When I change "loggerBladeExtended" in config file, nothing change. But, if i change in vendor config file then it's changing. I don't want to any change in vendor files.

Can you help me for this issue?

Thanks.

**Comment by jeremykenedy** [comment]
Thank you for reporting this. This has been fixed in the commit https://github.com/jeremykenedy/laravel-logger/commit/a973d9026b25b10369e2ae51f9e9074098737620
