### ISSUE TITLE
laravelcollective/html is abandoned, laravellux/html looks like a replacement candidate

### ISSUE THREAD

**Issue by denydias** [jeremykenedy/laravel-logger#162]
From [LaravelCollective](https://laravelcollective.com/thanks) website:

> Given this pattern, I think it's best to retire these packages rather than potentially open unsuspecting applications to a potential attack.

The author suggests `spatie/laravel-html`, but that would be a huge effort as the code patterns are way too different from the former.

A bit before the above quote the author says:

> Anyone can freely take it and begin their own journey, it will be a journey that belongs to them.

Well, it looks this is [done](https://github.com/LaravelLux/html#readme) now:

> ⚠️ Important Update: The `laravellux/html` package has replaced the `laravelcollective/html` package. Please replace all references of `Collective\Html` in your project with `LaravelLux\Html`. For the majority of applications, no other changes should be necessary, and your project should continue to work as expected. However, always ensure to thoroughly test your project after this update to avoid unexpected issues. Thank you for your understanding.

I haven't tested it, but it looks like a pretty straightforward, drop-in replacement. So I kindly ask you to replace the now abandoned `laravelcollective/html` in favor of `laravellux/html`.

**Comment by arborrow** [comment]
I would be curious to see what people think is best spatie or laravellux. The LaravelLux solution looks like a straightforward fork of the LaravelCollective/html project so obviously that will be the simplest to make That said, the fact that there is a shift available from Laravel Shifts to move to the Spatie package seems to show that the community is generally in favor of that approach. I relied heavily on LaravelCollective/html in one of my projects but the shift did well with the exception of Form::Image which needs some tweaking. I think either would be a good solution for this project. I would welcome others feedback.

**Comment by denydias** [comment]
Spatie looks like the preferred and obvious upgrade path as it's mentioned by laravelcollective/html and already supported by Shift.

Anyway, to me it doesn't look as a matter of what Laravel influencers decided to be the preferred path. Projects using laravel-logger may be using it long enough and well enough to avoid other newer, expensive solutions. IMHO it doesn't look like 'what is the best' issue... it's more like to keep having choices apart from the packages sponsored by Laravel superstars while keeping a straightforward path to upgrade projects relying on this package.

**Comment by arborrow** [comment]
I do not have a strong opinion one way or the other. I think in some ways, it makes sense when possible to go with the mainstream. I've been a happy user of this project for a good while and grateful for the work done. I'm all for healthy diversity as well. Ultimately, I support whatever the maintainer thinks is best.

**Comment by jeremykenedy** [comment]
I need to land will look at this more when I get a chunk of time in the near future.

**Comment by arborrow** [comment]
Sounds good, let me know if there is anything I can do to be supportive.

**Comment by jeremykenedy** [comment]
Thank you,

This has been updated in PR https://github.com/jeremykenedy/laravel-logger/pull/171
