### ISSUE TITLE
Help to Disable GeoPlugin

### ISSUE THREAD

**Issue by TopL0ader** [jeremykenedy/laravel-logger#164]
Thank you for the great app along with laravel auth which was running superb until my page loads have gone in excess of 60s due to what my service provider informs me that 

"we see your server attempts to connect to host 178.237.33.50 port 80 (http) multiple times without receiving any reply back from it which confirmed our suspicion. Perhaps that external host has firewalled you out?"

For the life of me I can not stop my app trying to connect to 178.237.33.50 (geoplugin.com)

As a matter of urgency please help?

**Comment by jeremykenedy** [comment]
Geo data comes from using this trait.

https://github.com/jeremykenedy/laravel-logger/blob/master/src/App/Http/Traits/IpAddressDetails.php

you can override them route to map to your controller which can extend off the packages controller. Within your customer controller overwrite the method with how it suits you and not using the geo data.

**Comment by TopL0ader** [comment]
Morning,

I have removed logger with every intention of installing again once I resolve the issues with geoplugin but still I have an hangtime of 60s as it calls the geoplugin.

I have removed every trace I think that refers to laravel logger.

Please explain the above resolution

**Comment by jeremykenedy** [comment]
Cached configuration. 

"Php artisan cache:clear && php artisan config:cache"

**Comment by TopL0ader** [comment]
Apologies it still attempts to connect to host 178.237.33.50 port 80 (http) multiple times without a response causing a 60s delay in loading.

I am using laravel auth (yours) and no customer controller (user controller as per your app) and I do not understand 

"you can override them route to map to your controller which can extend off the packages controller"

Please please inform me how i can solve this (idiots guide)

Sincere apologies and i appreciate your busy

**Comment by TopL0ader** [comment]
Sorted thank you.

**Comment by TopL0ader** [comment]
It was laravel-blocker using the same geoPlugin

**Comment by jeremykenedy** [comment]
Ahhh, good catch
