### ISSUE TITLE
Activity Lot Item Blade Incorrect Variable Name

### ISSUE THREAD

**Issue by gente002** [jeremykenedy/laravel-logger#18]
In line 383 of activity-log-item.blade.php it references an $activities variable.  I think this should be $activity.

```
@if(config('LaravelLogger.loggerDatatables'))
        @if (count($activity) > 10)
            @include('LaravelLogger::scripts.datatables')
        @endif
@endif
```

**Comment by jeremykenedy** [comment]
This has been updated in commit https://github.com/jeremykenedy/laravel-logger/commit/2def2ac35cebc98219d416d892af02b9b46ab967
