### ISSUE TITLE
dont work the button 

### ISSUE THREAD

**Issue by crosasga** [jeremykenedy/laravel-logger#2]
![prtscr](https://user-images.githubusercontent.com/22960856/35702483-0182e906-0778-11e8-82a0-d93140dc04b9.jpg)

dont work the button

**Comment by jeremykenedy** [comment]
Please tell me more info

**Comment by crosasga** [comment]
I have laravel 5.4 with php 7.1 and mysql this on local instance,  when pressing the button does nothing, in console or log does not appear anything does not raise any modal or pop up

**Comment by jeremykenedy** [comment]
In your applications `app.blade.php` before the closing `</head>` tag add the following:
```
@yield('template_linked_css')
```

And before the closing `</body>` tag add the following:
```
@yield('footer_scripts')
```
