### ISSUE TITLE
Generating wrong url

### ISSUE THREAD

**Issue by azorpax** [jeremykenedy/laravel-logger#21]
https://github.com/jeremykenedy/laravel-logger/blob/a973d9026b25b10369e2ae51f9e9074098737620/src/resources/views/logger/partials/activity-table.blade.php#L137
--------
Hi, I am not sure if I'm the only one who encountered this bug or not bug?
The URL is generating like this:
`mywebsite.com/http://mywebsite.com/xxxxx/xxx`

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-logger/blob/master/README.md#opening-an-issue

**Comment by azorpax** [comment]
Done starring the repo. Now will you consider my two issues?

**Comment by azorpax** [comment]
Are you still working into this?

**Comment by jeremykenedy** [comment]
I haven't had time and most likely will not until this weekend. Thank you for letting me know and for all the contributions lately.

**Comment by jeremykenedy** [comment]
This has been fixed in the PR https://github.com/jeremykenedy/laravel-logger/commit/7e54957c6ca0ff1025f116fdae0ac5355d7f629f

Thank you again! :)
