### ISSUE TITLE
LaravelLoggerController.php on line 12: "App\Http\Controllers\Controller" hardcoded

### ISSUE THREAD

**Issue by peyobr** [jeremykenedy/laravel-logger#3]
Just installed:

PHP Fatal error:  Class 'App\Http\Controllers\Controller' not found in /vendor/jeremykenedy/laravel-logger/src/app/Http/Controllers/LaravelLoggerController.php on line 12

My application have app:name set.

Is it possible to override

Thank you.

**Comment by jeremykenedy** [comment]
I cannot duplicate. Make sure you followed all the installation steps.

**Comment by peyobr** [comment]
Please read carefully the issue subject: your controller extend default App\Http\Controllers\Controller.

This make your package unusable if application namespace has been changed using "php artisan app:name" (i.e. "MyApp")

**Comment by jeremykenedy** [comment]
Then it looks like you will need to mak changes to support “your” custom application.

**Comment by peyobr** [comment]
Simply extending: Illuminate\Routing\Controller

I'll submit PR asap

thak you

**Comment by jeremykenedy** [comment]
Awesome, thank you
