### ISSUE TITLE
User primary key

### ISSUE THREAD

**Issue by userbig** [jeremykenedy/laravel-logger#32]
My user model has a custom primary key (integer, yes), and logger fetching only 'id' row. How to change it? 

Thanks.

**Comment by jeremykenedy** [comment]
Hello,

There are 2 things that would need to be done and one can be handled by your app and the other will have be thought through how to handle it.

1. A migration will need to be made to update the table. See https://github.com/jeremykenedy/laravel-logger/blob/master/src/database/migrations/2017_11_04_103444_create_laravel_logger_activity_table.php#L27

2. The rules will need to be updated somehow. Currently, they are part of the package that is not editable. To make this editable some modifications to the package would need to be made. One idea would be to make the rules extend off the service providers config file.

Thanks,


https://github.com/jeremykenedy/laravel-logger/blob/master/src/app/Models/Activity.php#L131
