### ISSUE TITLE
/src/app/Http/Middleware/LogActivity.php - Line No. 39 not updating while composer update

### ISSUE THREAD

**Issue by anishbangalore** [jeremykenedy/laravel-logger#43]
Dear Friend,
I installed version 1.1.0 with the composer.json entry "jeremykenedy/laravel-logger": "^1.0" but the update you mentioned in commits are not getting, still i am getting the file with out '[ ]' in shouldLog function.

```
protected function shouldLog($request)
    {
        foreach (config('LaravelLogger.loggerMiddlewareExcept') as $except) {
            if ($except !== '/') {
                $except = trim($except, '/');
            }

            if ($request->is($except)) {
                return false;
            }
        }

        return true;
    }
```

and this is throwing error, what procedure I need to follow to get the updated line number 39

thanks,
Anish

**Comment by jeremykenedy** [comment]
You have to publish the config file and add the entry’s from the .env file.

**Comment by anishbangalore** [comment]
Yes I did what all described in https://github.com/jeremykenedy/laravel-logger, also i removed the existing files and added again using composer before I posted here, As of now I edited the LogActivity.php line number 39 myself, But I know this is not a permanent solution, that's why I posted my experience here. Hope we can find a better solution.

I am using vagrant2.2.2 with VirtualBox6.0.0

Thanks
