### ISSUE TITLE
User Agent is not correctly parsed

### ISSUE THREAD

**Issue by PrimeGhostDE** [jeremykenedy/laravel-logger#44]
Hello Jeremy,

first of all, nice project. Well done.

I noticed, that the User Agent in the List of Activites of Laravel-Auth Project is not properly displayed.
To do so I overrided the View. But instead it would be better to override the model. (That shouldnt be done by me - due to updates or so)

My fix is:
Added before Line 153 of File resources/views/logger/partials/activity-table.blade.php

that:

`$userAgentDetails = \jeremykenedy\LaravelLogger\App\Http\Traits\UserAgentDetails::details($activity->userAgent);`

and changed following 3 Lines.

Your Fix I would recommend would be adding to the Model of Activity this Function:
```
public function getUserAgentDetailsAttribute() {
  return \jeremykenedy\LaravelLogger\App\Http\Traits\UserAgentDetails::details($this->userAgent);
}
```

I hope I could help you with that.

PrimeGhost

**Comment by jeremykenedy** [comment]
This has been added to the model in the most recent release. 

https://github.com/jeremykenedy/laravel-logger/commit/18719e14e676febd9cd7c86328cdf3bfd1c98cac

Thank you.
