### ISSUE TITLE
Unable to load log file.

### ISSUE THREAD

**Issue by EeSien** [jeremykenedy/laravel-logger#47]
When i was trying to go to /logs , it able to display the log . But when i  was trying to select the log file based on date, it shows
 Illuminate \ Contracts \ Encryption \ DecryptException
The payload is invalid.

i can only fix this problem by command out the line 46 and 50 in logviewercontroller.

Is there any other way i can fix this error?

![image](https://user-images.githubusercontent.com/26835915/53159911-cb964180-3601-11e9-9613-4f466ee5e07b.png)

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-logger#opening-an-issue

**Comment by EeSien** [comment]
Hi jeremy, it about the log files but not the activity log. 

When i go to the log file page and trying to select the previous log file to check error content, it show me The payload is invalid.

**Comment by jeremykenedy** [comment]
```/logs``` Are not a route that is even part of this repo.
