### ISSUE TITLE
Feature: Add a different user when logging an activity.

### ISSUE THREAD

**Issue by smartsyncio** [jeremykenedy/laravel-logger#53]
Hi,

I have just come across an issue when using the logger to log what happens inside a JOB. The activity is recorded as 'guest'

Being able to do something like the following would be helpful in this instance :
ActivityLogger::activity("I have logged something.", $activeUser);

Regards

**Comment by jeremykenedy** [comment]
The is because the default log type is guest: https://github.com/jeremykenedy/laravel-logger/blob/master/src/app/Http/Traits/ActivityLogger.php#L21

Do you have any suggestions for seeing if the event was triggered by a job?

**Comment by jeremykenedy** [comment]
Closing the issue due to non response.
