### ISSUE TITLE
Feature: Allow customisation of routes

### ISSUE THREAD

**Issue by hsgce** [jeremykenedy/laravel-logger#54]
I think this would be a good feature to add.

I think the best way to do this would be similar to how the base laravel auth routes are registered.

You would add `LaravelLogger::routes()` to your routes file for your app, and this would take an array of config options, such as:
- route prefix
- route name prefix
- middleware
- routes to disable
etc

This would be applied to the routes, which would then be added to the app's router routes.
Obviously would have to make it backwards compatible.

The other way would be to allow you to disable the routes with a config option, and then you could add them yourself to your routes file (using the full controller namespace + name)

I'll try and get a PR up when I have a chance :)

This is related to #17

**Comment by jeremykenedy** [comment]
I will keep an eye out for it. 

Thanks,

**Comment by atymic** [comment]
FYI PR is up in #55 😄

**Comment by matrunchyk** [comment]
Awesome package! Could you please release this issue?

**Comment by jeremykenedy** [comment]
Created release. Thanks for catching that.

**Comment by matrunchyk** [comment]
Great, thank you. The only thing - 3 releases before there was v2.4.2 published, and then 1.1.1, and then 1.2.0. Is that intentional?
I have a record in my composer.json where states `"jeremykenedy/laravel-logger": "^2.4",`, so the newly published versions won't be installed. 
Should I change it to `"jeremykenedy/laravel-logger": "^1.2",` ?

**Comment by jeremykenedy** [comment]
Good catch, that’s just a bonehead error on my part. All fixed :)

**Comment by matrunchyk** [comment]
Thanks a lot! :)
