### ISSUE TITLE
tooltip fails requiring Popper.js

### ISSUE THREAD

**Issue by vwasteels** [jeremykenedy/laravel-logger#56]
I get this error : 
`jquery-3.2.1.slim.min.js:2 Uncaught TypeError: Bootstrap tooltips require Popper.js`

and the dropdown menu can't show up.

this is the layout I'm using : 
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    @yield('template_linked_css')
  </head>
  <body>
    @yield('content')
    @yield('footer_scripts')
  </body>
</html>
```

pretty basic,

see screenshots of the errors : 
![Screenshot -  2019-06-20 à 11 47 47](https://user-images.githubusercontent.com/1151398/59839999-dbc0f200-9351-11e9-8f94-fd4e1bec8c50.jpg)
![Screenshot -  2019-06-20 à 11 48 04](https://user-images.githubusercontent.com/1151398/59840000-dc598880-9351-11e9-8fc2-97ab615ef818.jpg)

any though ?

thanks, love

**Comment by vwasteels** [comment]
issue closed ?
did I miss something ?

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-logger#opening-an-issue

Its a configuration error within your app.
