### ISSUE TITLE
laravelcollective/html missing in dependencies

### ISSUE THREAD

**Issue by vwasteels** [jeremykenedy/laravel-logger#57]
note : I did read the instructions for opening an issue.

On a fresh install, here is the history : 
```bash
composer global require laravel/installer\n
laravel new logger-error
cd logger-error
php artisan make:auth
php artisan migrate
composer require jeremykenedy/laravel-logger
php artisan migrate
php artisan vendor:publish --tag=LaravelLogger
```

when fetching this url : http://logger-error.test/activity
I get : 

```
Class 'Form' not found (View: /Users/vwasteels/code/logger-error/resources/views/vendor/LaravelLogger/forms/clear-activity-log.blade.php) (View: /Users/vwasteels/code/logger-error/resources/views/vendor/LaravelLogger/forms/clear-activity-log.blade.php)
```

Solved with : 
`composer require "laravelcollective/html":"^5.8.0"`

**Comment by jeremykenedy** [comment]
Yep, I just need to add that to composer.json until I strip that out. Thanks

**Comment by jeremykenedy** [comment]
This has been updated with https://github.com/jeremykenedy/laravel-logger/commit/2d838a8b24f8a4abcc952aac4191d75fb8d14e53

Thanks,
