### ISSUE TITLE
loadMigrationsFrom call causes mysql to be used even if pgsql is specified everywhere.

### ISSUE THREAD

**Issue by rwdcorp** [jeremykenedy/laravel-logger#58]
First off, love it... Great work. You have saved countless millions of developer hours because of the work you've done.  Keep up the great work.

Buuuuuut... (sorry)...

Due to the call to loadMigrationsFrom in the service providers of this and other dependencies of laravel-auth, in conjunction with the vendor code being unaware of the configs above it in app/config, the vendor code always tries to use MySql, even if everything in the env and app/config says to use pgsql.   

Please, please, puhleeze, make loadMigrationsFrom (and other vendor/location forcing) calls optional via top-level config. Publishing to app/database/migrations does not stop vendor code from running in loadMigrationsFrom is called in your providers register/boot functions.

Despite the appearance below, all my other tables are created in the Pgsql database, but processing stops when it hits laravel-logger (and other laravel-auth deps)...

``` 
1   PDOException::("PDO::__construct(): MySQL server has gone away")
    /Users/devdude/Projects/mydb.dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

2   PDO::__construct("mysql:host=127.0.0.1;port=5432;dbname=mydb", "mydb", "mydb", [])
    /Users/devdude/Projects/mydb.dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

3   Doctrine\DBAL\Driver\PDOConnection::__construct("mysql:host=127.0.0.1;port=5432;dbname=mydb", "mydb", "mydb", [])
    /Users/devdude/Projects/mydb.dev/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67

4   Illuminate\Database\Connectors\Connector::createPdoConnection("mysql:host=127.0.0.1;port=5432;dbname=mydb", "mydb", "mydb", [])
    /Users/devdude/Projects/mydb.dev/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:100

5   Illuminate\Database\Connectors\Connector::tryAgainIfCausedByLostConnection(Object(Doctrine\DBAL\Driver\PDOException), "mysql:host=127.0.0.1;port=5432;dbname=mydb", "mydb", "mydb", [])


```

**Comment by jeremykenedy** [comment]
The packages uses the database you specify in your .env file as indicated here: 

https://github.com/jeremykenedy/laravel-logger/blob/master/src/config/laravel-logger.php#L11

The migration uses that connection as indicated here:
https://github.com/jeremykenedy/laravel-logger/blob/master/src/database/migrations/2017_11_04_103444_create_laravel_logger_activity_table.php#L18

The migration called that from the model as indicated here:
https://github.com/jeremykenedy/laravel-logger/blob/master/src/app/Models/Activity.php#L96
https://github.com/jeremykenedy/laravel-logger/blob/master/src/app/Models/Activity.php#L24

My first thought is you may have to clear your autoloader settings with:
`composer dump-autoload`

**Comment by jeremykenedy** [comment]
Did the above resolve the issue?
