### ISSUE TITLE
Clear activity doesn't work

### ISSUE THREAD

**Issue by SamyOteroGlez** [jeremykenedy/laravel-logger#65]
First of all, AMAZING JOB!!!

The issue:

When clicking on `Clear Activity Log`, and then click on `Confirm` in the confirmation modal, it does nothing, no closing the modal, no sending the request, no js error.

Also, I set to false the use of all the js/css files: jquery, bootstrap, etc
I am using instead:
 - jquery 3.3.1
 - propper 1.14.7
 - bootstrap 4.3.1

I can also confirm that none of the confirms modals are working for me. I assume it could be js related since I changed the button type to submit on all of them and the forms are submitted (clear logs, restore logs, delete logs).

I hope this info helps.

Cheers,
Sam

**Comment by SamyOteroGlez** [comment]
Any update?

**Comment by texnika01** [comment]
it doesn't work for me even after the change .

**Comment by SamyOteroGlez** [comment]
@texnika01 A workaround I found is, after publishing the views, find the templates responsible where the forms (clear activity and delete forever), and remove the js call from the form and set the button type to submit. It will do the clear and the deletion without the confirmation modal/confirmation.

If you are fine with that for the moment.

Cheers

**Comment by texnika01** [comment]
I'll give it a try. Тhank you
