### ISSUE TITLE
Conclusion: remove laravel/framework v5.1.46

### ISSUE THREAD

**Issue by FoxRocks76** [jeremykenedy/laravel-logger#70]
I'm running Laravel 5.1 and I keep getting this error when I try to install this plugin:

Problem 1
    - The requested package laravelcollective/html (locked at v5.1.11, required as ^5.8.0) is satisfiable by laravelcollective/html[v5.1.11] but these conflict with your requirements or minimum-stability.

I think I'm locked to the laravelcollective/html[v5.1.11] because I'm on Laravel 5.1.46. I'm following the guide by using "composer require jeremykenedy/laravel-logger" but it fails. I was able to install an older version successfully by running "composer require jeremykenedy/laravel-logger:dev-bootstrap3"

**Comment by jeremykenedy** [comment]
Yeah this package doesn’t have support for 5.1.

I would say fork it, make the changes, and add it to composer.

**Comment by FoxRocks76** [comment]
Ok, it did say it worked with Laravel 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, and 5.7+, but nonetheless I think the boostrap3 version will work. Thanks!!

**Comment by jeremykenedy** [comment]
It’s not an issue with this package it’s an issue with the html dependency

**Comment by FoxRocks76** [comment]
Hi Jeremy,
I've been digging through this and I don't believe this package works with Laravel v5.1. Reason being is that the frameworks ServiceProvider.php doesn't have two of the methods required by LaravelLoggerServiceProvider.php, specifically `loadRoutesFrom` and `loadMigrationsFrom`, which don't appear until v5.3.
