### ISSUE TITLE
multiple  custom defaultUserIDField and defaultUserModel

### ISSUE THREAD

**Issue by TechNov** [jeremykenedy/laravel-logger#71]
Hello ,
I user laravel 5.8 and i have two table fos two differents ayhtenticate milddleware.
Tablem User_client ( with defaultUserIDField 'id')  and table Administrators ( with defaultUserIDField 'idadmin') 
My question is how to implements those mutilple custom Id and mutilple custom Models in laravel-logger.php file or .env?
thank

**Comment by jeremykenedy** [comment]
You have to pick one. The feature to use a custom key is a new feature and it only allows one primary key
