### ISSUE TITLE
Logged IP is wrong if behind a proxy

### ISSUE THREAD

**Issue by HadrienKulik** [jeremykenedy/laravel-logger#73]
I think the line
`'ipAddress'     => Request::ip(),`
should be changed to something like
`'ipAddress'     => request()->server('HTTP_X_FORWARDED_FOR') ? request()->server('HTTP_X_FORWARDED_FOR') : Request::ip(),`
if we want to log the real IP of the client (website behind Cloudflare, etc.)

Also, not sure of the utility of these lines in the `IpAddressDetails` Trait :
```
            if ($deep_detect) {
                if (filter_var(@$_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP)) {
                    $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
                }
                if (filter_var(@$_SERVER['HTTP_CLIENT_IP'], FILTER_VALIDATE_IP)) {
                    $ip = $_SERVER['HTTP_CLIENT_IP'];
                }
            }
```
I think that should be done before the logging is persisted to database, otherwise the $_SERVER variables are out of context of the actual page visit.

**Comment by HadrienKulik** [comment]
@jeremykenedy what do you think?

FYI I also found a bug in the links to see the details of the logs, if the activity pages are not installed at the root of the application. 
`$prependUrl = '/activity/log/';` does not take into account the context of the installation.

Do you want me to note the issues I find or not? Not sure as you closed this issue with no comment.

Great package otherwise ;)

**Comment by jeremykenedy** [comment]
Issue was closer because it didn’t follow the guidelines outlined in the readme:

https://github.com/jeremykenedy/laravel-logger#opening-an-issue

**Comment by jeremykenedy** [comment]
Today I came across this article which I may add to this package for cloudflare detection: 

https://stackoverflow.com/questions/14985518/cloudflare-and-logging-visitor-ip-addresses-via-in-php/14985633#14985633
