### ISSUE TITLE
User field gets empty value in some cases.

### ISSUE THREAD

**Issue by stockarea** [jeremykenedy/laravel-logger#79]
I don't know what is your criteria for checking the user name. But most of my entires have the user coming as nothing. its empty. 
`userid` column is getting filled as null in most of the cases.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-logger#opening-an-issue

https://github.com/jeremykenedy/laravel-logger/blob/master/src/app/Http/Traits/ActivityLogger.php#L27

https://github.com/jeremykenedy/laravel-logger/blob/master/src/config/laravel-logger.php#L74

https://github.com/jeremykenedy/laravel-logger/blob/master/src/.env.example#L9
