### ISSUE TITLE
Object not found! when opening log details

### ISSUE THREAD

**Issue by VinceGee** [jeremykenedy/laravel-logger#81]
First of all, great package.

However I am facing this problem when I try to drill down on an activity, to get all the details.

When I was developing using `pa serve`, I had no challenges regarding to this, I could view all the details of an activity. But Im now running my project without `pa serve`, directly in the WebBrowser I type: localhost/myproject to access my project.

however when I try to drill down on an activity its redirecting to: `http://localhost/activity/log/1087` and if I manually include myproject .i.e. `http://localhost/myproject/activity/log/1087` its opening just fine.

I tried changing the URL in `\vendor\jeremykenedy\laravel-logger\src\resources\views\logger\partials\activity-table.blade.php` from `$prependUrl = '/activity/log/';` to `$prependUrl = '/myproject/activity/log/';` then ran php config:cache, route:cache,view:cache. It did not change anything.

I also tried changing the URL format to {{url('/myproject/activity/log/')}} but that did not change anything as well.

**Comment by jeremykenedy** [comment]
It’s an environmental configuration issue. Look into serving your Laravel project from the root folder and not a sub directory.
