### ISSUE TITLE
Class App\Http\Controllers\jeremykenedy\LaravelLogger\App\Http\Controllers\LaravelLoggerController does not exist

### ISSUE THREAD

**Issue by ahph37** [jeremykenedy/laravel-logger#84]
Why i have exception like this
"Class App\Http\Controllers\jeremykenedy\LaravelLogger\App\Http\Controllers\LaravelLoggerController does not exist"
when i want to acces route /activity?
@jeremykenedy

**Comment by stanley87** [comment]
@ahph37 has your side fix this issue?i am having same issue when using this package

**Comment by jeremykenedy** [comment]
Are you implementing as outlined in the docs? 

Are you doing anything different like trying to define your own routes in web.php?

The issue was originally closed because it did not have enough information to replicate as outlined here: https://github.com/jeremykenedy/laravel-logger#opening-an-issue

**Comment by stanley87** [comment]
yes,i am using the i own routes like this

Route::group(['prefix' => 'activity', 'namespace' => 'jeremykenedy\LaravelLogger\app\Http\Controllers', 'middleware' => ['web', 'auth', 'activity']], function () {

//     // Dashboards
//     Route::get('/', 'LaravelLoggerController@showAccessLog')->name('activity');
//     Route::get('/cleared', ['uses' => 'LaravelLoggerController@showClearedActivityLog'])->name('cleared');

//     // Drill Downs
//     Route::get('/log/{id}', 'LaravelLoggerController@showAccessLogEntry');
//     Route::get('/cleared/log/{id}', 'LaravelLoggerController@showClearedAccessLogEntry');

//     // Forms
//     Route::delete('/clear-activity', ['uses' => 'LaravelLoggerController@clearActivityLog'])->name('clear-activity');
//     Route::delete('/destroy-activity', ['uses' => 'LaravelLoggerController@destroyActivityLog'])->name('destroy-activity');
//     Route::post('/restore-log', ['uses' => 'LaravelLoggerController@restoreClearedActivityLog'])->name('restore-activity');
// });

**Comment by stanley87** [comment]
my side even try use custom vendor path load like below,still facing same issue too

 "psr-4": {
            "App\\": "app/",
            "jeremykenedy\\LaravelLogger\\": "vendorcustom/jeremykenedy/laravel-logger/src/"
        }

**Comment by jeremykenedy** [comment]
The routes are built int to the package and wrapped in group that assigned the namespace.

https://github.com/jeremykenedy/laravel-logger/blob/master/src/routes/web.php

```
Route::group(['prefix' => 'activity', 'namespace' => 'jeremykenedy\LaravelLogger\App\Http\Controllers', 'middleware' => ['web', 'auth', 'activity']], function () {
...
});
```

**Comment by azuan85** [comment]
Adding '**\**' before namespace solve my problem

Route::group(['prefix' => 'admin/activity', 'namespace' => '**\jeremykenedy\LaravelLogger\App\Http\Controllers**', 'middleware' => ['web', 'auth', 'activity']], function () {

**Comment by PositiveZahid** [comment]
Adding \ before namespace solve my problem

Route::group(['prefix' => 'admin/activity', 'namespace' => '\jeremykenedy\LaravelLogger\App\Http\Controllers', 'middleware' => ['web', 'auth', 'activity']], function () {

> Adding \ before namespace solve my problem
> 
> Route::group(['prefix' => 'admin/activity', 'namespace' => '**\jeremykenedy\LaravelLogger\App\Http\Controllers**', 'middleware' => ['web', 'auth', 'activity']], function () {

Thanks
