### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by netstreet** [jeremykenedy/laravel-logger#85]
Hi..

how i solve this issue

> Class jeremykenedy\LaravelBlocker\Database\Seeds\DefaultBlockedItemsTableSeeder located in ./vendor/jeremykenedy/laravel-blocker/src/database/seeds/DefaultBlockedItemsTableSeeder.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

this is only one row the errors

**Comment by jeremykenedy** [comment]
Composer 2 in beta and 1 is the standard.

**Comment by jeremykenedy** [comment]
https://getcomposer.org/

**Comment by netstreet** [comment]
Yes i know composer 2.0 that issue come when i upgrade composer version 
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer 1.9.0 2019-08-02 20:55:32
