### ISSUE TITLE
Feature request: The ability to log API activity

### ISSUE THREAD

**Issue by ubisales-bradley** [jeremykenedy/laravel-logger#91]
It would be brilliant if you could log the API activity within the same page, the log would be perfect if it followed this: 

https://support.airship.com/hc/en-us/articles/213491283-Best-practices-for-using-the-API-and-why-you-should-log-your-activity

So helpful when fixing bugs!

**Comment by jeremykenedy** [comment]
I would gladly accept a PR for this :)
