### ISSUE TITLE
PR inquiry: config option to extended activity model

### ISSUE THREAD

**Issue by denydias** [jeremykenedy/laravel-logger#94]
Hi @jeremykenedy! First of all let me tank you for your awesome work. Your Laravel packages are just great! I'm developing an app for my own business and your work is being very helpful. Rest assured you'll be remembered when the time to share the appreciation arrives. :money_mouth_face:

laravel-roles has the following set of options:

```php
'models' => [
    'role'          => env('ROLES_DEFAULT_ROLE_MODEL', jeremykenedy\LaravelRoles\Models\Role::class),
    'permission'    => env('ROLES_DEFAULT_PERMISSION_MODEL', jeremykenedy\LaravelRoles\Models\Permission::class),
    'defaultUser'   => env('ROLES_DEFAULT_USER_MODEL', config('auth.providers.users.model')),
],
```

This makes very easy to use custom models, for which I'm deeply thankful.

Now with laravel-logger I'm in the need extend the Activity model with something like this:

```php
<?php

namespace App\Models;

use jeremykenedy\LaravelLogger\App\Models\Activity as VendorActivityModel;

class Activity extends VendorActivityModel
{
    /**
     * Set microsecond precision datetime.
     *
     * @var string $dateFormat
     */
    protected $dateFormat = 'Y-m-d H:i:s.u';
}
```

To make use of this extended model I need to refactor a lot of code as App\Http\Traits\ActivityLogger has App\Models\Activity hard coded in it.

So I ask: if I provide a pull request for making the Activity model configurable, would you be willing to accept it or do you have anything against this kind of change?

Thank you again for your time.

**Comment by jeremykenedy** [comment]
Hello, I’ll consider a PR as long as it’s 100% backwards compatible with no further configuration needed and done cleanly in Laravel conventions. Thanks

**Comment by denydias** [comment]
Thank you for the reply. I understand your concern about backward compatibility and Laravel conventions. I will try my best to accomplish it.

Regarding configuration, there will be the need of at least one configuration so one could choose the model to implement, e.g.:

```php
'defaultLoggerModel' => env('LARAVEL_LOGGER_DEFAULT_MODEL', jeremykenedy\LaravelLogger\App\Models\Activity'::class)
```

Is it acceptable?
