### ISSUE TITLE
Unable to confirm on clear activity log

### ISSUE THREAD

**Issue by arborrow** [jeremykenedy/laravel-logger#96]
I'm using roles middleware (can with a permission) but unable to confirm to clear activity logs. I can cancel the confirmation but clicking on the confirm button does not seem to do anything.

**Comment by katesaikishore** [comment]
Same here

**Comment by katesaikishore** [comment]
Viewes=>Vendor=>LarvelLogger=>forms=>clear-activity-log.blade.php

Replace with
'type' => 'sumbit',

So that you can directly delete the rows, Happy logging 💯

**Comment by urameshibr** [comment]
My solution is not the correct, BUT, works:

1- open the file `resources/vendor/LaravelLogger/modals/confirm-modal.blade.php`

2- Search for the div `<div class="modal-footer">`

3- Add the form tags BEFORE the button tags:
```
{!! Form::open(array('route' => 'clear-activity')) !!}
{!! Form::hidden('_method', 'DELETE') !!}
```

4- Close the form tag BEFORE the finish of `<div class="modal-footer">` tag and AFTER the button tags:
`{!! Form::close() !!}`

5- Change the "type" attribute of the 2nd button tag: from "button" to "submit"
`'type' => 'button',` -> `'type' => 'submit',`

5- Print of the result:

![image](https://user-images.githubusercontent.com/5429620/167666324-244de80d-6780-4873-8656-a801639bbedc.png)

**Comment by urameshibr** [comment]
@katesaikishore 

This is a problem with the javascript, the js code must to execute after load all the jquery lib.

For to solve, just do that.

Envolve the code of the file `resources/views/vendor/LaravelLogger/scripts/confirm-modal.blade.php`

with 
```$(function() {
 // the javascript file code
})```

Print of example:

![image](https://user-images.githubusercontent.com/5429620/167681194-cb5120bd-414a-4e30-adf7-7740a26552bc.png)
