### ISSUE TITLE
Where is the ipAddress cast defined? 

### ISSUE THREAD

**Issue by arborrow** [jeremykenedy/laravel-logger#97]
I was looking to upgrade to Laravel 8; however, one error that I began receiving was:

Call to undefined cast [ipAddress] on column [ipAddress] in model [jeremykenedy\LaravelLogger\App\Models\Activity]. 

I see that the cast type is ipAddress but I do not see any custom casts. https://laravel.com/docs/7.x/eloquent-mutators#custom-casts does not list that as a valid cast type. I will look a little deeper but figured I would share my experience.

**Comment by spjan1** [comment]
I have the same error after upgrade to laravel 8. Im hoping for a quick laravel 8 support or a temporary workaround.

**Comment by arborrow** [comment]
@spjan1  My quick workaround was to avoid the cast and simply list it as a string since the ipAddress cast type does not exist. So if you change:  'ipAddress'     => 'ipAddress',
to:         'ipAddress'     => 'string',

in the vendor\jeremykenedy\laravel-logger\src\App\Models\Activity.php file it should be functional.

**Comment by arborrow** [comment]
I see that Laravel 8 added the checking and exception for invalid casts that was silently skipped before. So I consider this a bug. I will work on a quick PR for @jeremykenedy to consider.

**Comment by jeremykenedy** [comment]
I will consider any PR. Life has been busy lately so I haven’t had time to do any open source work.

**Comment by arborrow** [comment]
No worries, I completed understand I just submitted https://github.com/jeremykenedy/laravel-logger/pull/98
